### ISSUE TITLE
PA Review: User Authentication 

### ISSUE THREAD

**Issue by anthonykumasaka** [anthonykumasaka/KumaFlix#2]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components and Containers
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by Carly-Schaaf** [comment]
Hey Anthony, your site looks great. Here are a few bugs/suggestions I came across: 

-  [x] The main Netflix logo should link to "/" (which should go to the "watch on any device" page)
- [x] Has working demo login
-  [x] The "/login" page should not display a link to Log In, same for "/signup" (you still have login and sign up links at the very bottom of the page)
- [x]  Going to a random route /#/oweiniouewbrviuwebv should redirect or display a 404 page (does not work if you're on the root page "/")
- [x]  Errors should not stay on the page while switching between the /signup and /login forms
- [x] Work on styling your errors and the logout button/user greeting

**Comment by anthonykumasaka** [comment]
I made the changes. Check them out when you can. Thanks!

**Comment by anthonykumasaka** [comment]
My push to heroku failed. I'll let you know when it is working.

**Comment by anthonykumasaka** [comment]
its working now

**Comment by Carly-Schaaf** [comment]
Looks like your heroku site is not working :/

**Comment by anthonykumasaka** [comment]
Yeah I’m trying to get that fixed now. The same problem happened to Miso after we were both working on aws demo.

**Comment by anthonykumasaka** [comment]
I never got it to work even after finishing aws so i rolledback my commits to yesterday around noon. It should work now at heroku.

**Comment by Carly-Schaaf** [comment]
Looks great!
